### ISSUE TITLE
Add link from ttfautohint documentation

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ttfautohint-build#10]
@lemzwerg Thoughts about linking here from the ttfautohint documentation?  Particularly for macOS users who are building from source?

**Comment by chrissimpkins** [comment]
Or perhaps this https://github.com/fonttools/ttfautohint-py will be the better approach when stable?

cc @anthrotype

**Comment by anthrotype** [comment]
BTW, everything *should* be working now, except for `-T --ttfa-info` option that dumps the TTFA table to stdout (but that can be easily replaced by the command `ttx -o - -t TTFA font.ttf` so i'm in no urgency to implement it).

I will add some automated tests in the coming days and maybe push some binary wheels to PyPI so others can try it out without needing compilers.
