### ISSUE TITLE
The install script is incorrect

### ISSUE THREAD

**Issue by Trisia** [source-foundry/ttfautohint-build#33]
If you try to run the script below
```bash
git clone https://github.com/source-foundry/ttfautohint-build.git
cd ttfautohint-build
make
```

you may get error hit of this 
```bash
Build directory ttfautohint-build must not exist.
```
I think in the script `ttfautohint-build.sh` line 63 - 66
```bash
if test -d "$BUILD" -o -f "$BUILD"; then
  echo "Build directory \`$BUILD' must not exist."
  exit 1
fi
```
This problem should be repeated for the project name and build name, so I try commented on these lines, problem solve.

but next I get a new problem that is 

The bz2 type compression package is included in the script download dependency.
```bash
tar -xjvf "$HARFBUZZ.tar.bz2"
```
Using tar to extract the following error may be caused by the lack of zip2 dependencies
```bash
tar (child): lbzip2: Cannot exec: No such file or directory 
tar (child): Error is not recoverable: exiting now 
tar: Child returned status 2 
tar: Error is not recoverable: exiting now
```

**you must install libzip2 before you run this script.**

so I try to install this lib by yum 
```bash
yum install bzip2
```

sole!

**Comment by chrissimpkins** [comment]
Thanks for this report!  I really appreciate it.  

re: build directory check:

Do you recommend that the script just handles the build directory with `rm -rf` if found?  We need a clean directory structure for the build process as the build is currently designed.  

re: tar.bz2:

Are you able to unpack gzipped tar archives on Fedora with default lib installs?   This format is used for improved compression but we can change it.

**Comment by Trisia** [comment]
I think `rm -rf`  may not a good choose, yes we can get a clean environment, every time you run this script you will use curl download dependency package, some time network not work as we expected.

re: bz2
I think bz2 is nice, but my environment is centos7 mini, some lib may no included, etc libzip2.

**Comment by chrissimpkins** [comment]
You do not want to make changes to the script? If so we should leave this open.
