### ISSUE TITLE
Review license

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ttfautohint-build#8]
@lemzwerg 

@davelab6 forwarded the following article to me re public domain dedication of work intended to be open source licensed work:

https://meshedinsights.com/2017/03/16/public-domain-is-not-open-source/

This wasn't associated with this project, it was because we have run into issues with this public domain issue in Hack as a result of DejaVu upstream work that was committed to the public domain.  

Given the potential for unintended (I assume) consequences in some jurisdictions, I wanted to see if we can review the CC0 statement in this script.  Would you be opposed to a transition to an OSI approved license for the shell script here?

**Comment by lemzwerg** [comment]
CC0 is fine with me, thanks!

**Comment by davelab6** [comment]
That's the point :) what would you prefer after cc0? MIT?

**Comment by lemzwerg** [comment]
Ah, I misunderstood.  Actually, I don't care, and MIT is fine with me.

**Comment by chrissimpkins** [comment]
@lemzwerg thanks Werner.  I can make the edits

**Comment by chrissimpkins** [comment]
Converted as of https://github.com/source-foundry/ttfautohint-build/commit/dccfa1f359bcfd21038ae369b228819384f3c1e0

Thanks all!
